# a2z theme Configuration

# Header
menu:
  Ozlem: https://ozlem.akinbosoyezaimoglu.com/
  Deniz: https://deniz.akinbosoyezaimoglu.com/
  Temi: https://temi.akinbosoyezaimoglu.com/
  Blogs: /archives/
  Archives: /allarchives/
  Contact Us: /contact/

head_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  - https://fonts.googleapis.com/css?family=Cookie
  - css/lightbox.min
  - https://cdn.jsdelivr.net/npm/lightgallery@1.6.12/dist/css/lightgallery.min.css

head_js:
  - https://identity.netlify.com/v1/netlify-identity-widget.js
  - https://code.jquery.com/jquery-3.3.1.min.js
  - https://cdn.jsdelivr.net/combine/npm/lightgallery,npm/lg-autoplay,npm/lg-fullscreen,npm/lg-thumbnail,npm/lg-video,npm/lg-zoom,npm/lg-pager

body_js:
  - 'js/lightbox-plus-jquery.min.js'
  - js/main.js

disqus_shortname: akinbosoyezaimoglu-com
google_analytics: UA-131136908-1
github: t4top/akinbosoyezaimoglu.com
