# a2z theme Configuration

# Navbar menu
home: https://www.akinbosoyezaimoglu.com/
menu:
  Ozlem: https://ozlem.akinbosoyezaimoglu.com/
  Deniz: https://deniz.akinbosoyezaimoglu.com/
  Temi: https://temi.akinbosoyezaimoglu.com/
  Blogs: /posts/
  Archives: /allarchives/
  Contact Us: /contact/

# Authors icons
authors_icons:
  Ozlem: https://lh3.googleusercontent.com/p5wEId8nyb4-4BQaPR6las-3defd975sgHvSe2gk2p92zaNuDTh0FzHzxEN0Zb7GvD6Ec8psRxsuACM-NQIlQWkgiL0dV8LzuupohM76vFcOfy890-VwLPQeYQJXycaVGTUC-8ow93Q
  Deniz: https://lh3.googleusercontent.com/vjLUrsSIyTXMEycStJoSN7SdSGroJ6jzry4iJEUfcA4rqESSQt8QRa9CfadCYaq3aTlQ6qMU8AwM6O5DKbeE8UWBeGPdlLWR-dXwod4SpeqtClbScjrcrgEjBNv27TlsqbImMBF0XKw
  Temi: https://lh3.googleusercontent.com/HY9LSJmTIIgkiYernVjEc90KSMlbyGmb9fic5aS9HjcLL-iZ1-tLOTrM4vnw5H968EJL2iBvgxVkjeRbO-tOjPoUkh0EUSYqura7O8sSFZd5KiiY121AZitGHRKfhNdl4SigY2zmGoU

head_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  - https://fonts.googleapis.com/css?family=Cookie
  - css/lightbox.min
  - https://cdn.jsdelivr.net/npm/lightgallery@1.6.12/dist/css/lightgallery.min.css

head_js:
  - https://identity.netlify.com/v1/netlify-identity-widget.js

body_js:
  - https://code.jquery.com/jquery-3.3.1.min.js
  - 'js/lightbox.min.js'
  - https://cdn.jsdelivr.net/combine/npm/lightgallery,npm/lg-autoplay,npm/lg-fullscreen,npm/lg-thumbnail,npm/lg-video,npm/lg-zoom,npm/lg-pager
  - js/main.js

rss: atom.xml
disqus_shortname:
google_analytics:
github: t4top/akinbosoyezaimoglu.com
