# a2z theme Configuration

# Navbar menu
menu:
  Ozlem: https://ozlem.akinbosoyezaimoglu.com/
  Deniz: https://deniz.akinbosoyezaimoglu.com/
  Temi: https://temi.akinbosoyezaimoglu.com/
  Blogs: https://home.akinbosoyezaimoglu.com/posts/
  Archives: https://home.akinbosoyezaimoglu.com/allarchives/
  Contact Us: https://home.akinbosoyezaimoglu.com/contact/

# Authors icons
authors_icons:
  Ozlem: https://lh3.googleusercontent.com/PlaMqhT5uDu2MhdFD_WMYgPD_xZJcqd5UaGB2HynL4W3uWej1v_KCBwaPBY_Qum84QR3xJbAVsXjn-fbujyxDDBiJA_dgOdxQA=s120-p-k-lf-no
  Deniz: https://lh3.googleusercontent.com/4UAX3B5LIu9zYDGwsX_Ik7jPDv3ZmszYNsr7rH5g1INt4wWbRPL6pARYChbIulcHIFUvb4d3ek9uiip1MhSY8_RcHmBuzui0aQ=s120-p-k-lf-no
  Temi: https://lh3.googleusercontent.com/qLNA2uvcFe-V1uiXz5yFwChq_UXrR0MzWFdCB2D6Wduss-fP2rAQcKQ5tzvzNjK-_qwr1vNv6tr60kLsM-qN6BiWp1ECYeX1=s120-p-k-lf-no

head_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  - https://fonts.googleapis.com/css?family=Cookie
  - css/lightbox.min
  - https://cdn.jsdelivr.net/npm/lightgallery@1.6.12/dist/css/lightgallery.min.css

head_js:
  - https://identity.netlify.com/v1/netlify-identity-widget.js
  - https://code.jquery.com/jquery-3.3.1.min.js
  - https://cdn.jsdelivr.net/combine/npm/lightgallery,npm/lg-autoplay,npm/lg-fullscreen,npm/lg-thumbnail,npm/lg-video,npm/lg-zoom,npm/lg-pager

body_js:
  - 'js/lightbox.min.js'
  - js/main.js

rss: atom.xml
disqus_shortname: akinbosoyezaimoglu-com
google_analytics: UA-131136908-1
github: t4top/akinbosoyezaimoglu.com
